version: '3'
services:
  crypto_watch_server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    container_name: crypto_watch_server

  crypto_watch_client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: crypto_watch_client
