version: '3'
services:
  crypto_watch_server:
    build:
      context: ./server
    ports:
      - "8003:8003"
    container_name: crypto_watch_server

  crypto_watch_client:
    build:
      context: ./client
    ports:
      - "3003:3003"
    container_name: crypto_watch_client
